#!/usr/bin/bash

#ssh-keygen -t rsa
#info=`df -h |awk -F% '{print $1,$2}'|awk 'NR>1 && $5>30 {print $1"--"$5"%--"$6}'`
#echo ${info}
MAIL=("")

declare -A name
name=(['app1']='')
for key in ${!name[*]}
do
	if [ ${key} = 'server1' ]
	then
		info=`/usr/bin/rsh ${name[${key}]} -p 14001 -l admin df -h |awk -F% '{print $1,$2}'|awk 'NR>1 && $5>80 {print $1"--"$5"%--"$6}'`
	elif [ ${key} = 'op3' ]
	then
		info=`/usr/bin/rsh ${name[${key}]} -p 1407 -l admin df -h |awk -F% '{print $1,$2}'|awk 'NR>1 && $5>80 {print $1"--"$5"%--"$6}'`
	elif [ ${key} = 'app100' ] || [ ${key} = 'app101' ]
	then
		info=`/usr/bin/rsh ${name[${key}]} -p 15050 -l admin df -h |awk -F% '{print $1,$2}'|awk 'NR>1 && $5>80 {print $1"--"$5"%--"$6}'`
	else
		info=`/usr/bin/rsh ${name[${key}]} -p 14070 -l admin df -h |awk -F% '{print $1,$2}'|awk 'NR>1 && $5>80 {print $1"--"$5"%--"$6}'`
	fi
	if [ -n "${info}" ]
	then 
		echo ${key}":"${name[${key}]} >> tt.txt
		echo 'Filesystem--Use--Mounted on' >> tt.txt
		echo ${info} >> tt.txt
		echo >> tt.txt
	fi
done

#filesize=`ls -l tt.txt | awk '{ print $5 }'`
if [ -f 'tt.txt' ]
then
		for mail in ${MAIL[@]}
		do
			echo "To: ""${mail}" >> ./contact.txt
			echo 'From: houmian@mavericksmobile.com' >> ./contact.txt
			echo  "Subject: Disk Daily Check --- Disk space more than 80%" >> ./contact.txt
			echo 'Please check server '"${key}"':'"${name[${key}]}"',disk space is not enough!!' >> ./contact.txt
			echo	>> ./contact.txt
			echo 'Use Command: df -h' >> ./contact.txt
			echo 'Clean apachec/logs/: > error_log ... ' >> ./contact.txt
			echo 'more /etc/crontab/ -> do mon log clean ... ' >> ./contact.txt
			echo	>> ./contact.txt
			cat ./contact.txt tt.txt > ./.sendmail.txt;
			/usr/sbin/ssmtp ${mail} < ./.sendmail.txt;
			rm -rf ./contact.txt
		done
		rm tt.txt
fi


